import ThemeRegistry from "@/app/theme/NextThemeRegistry";
import ResponsiveAppBar from "./AppBar";
import Apollo from "@/app/providers/Apollo";
import { getRequestStorage } from "./lib/localStorage";
import { initializeApollo } from "./lib/apolloClient";
import { cookies } from "next/dist/client/components/headers";
import { CHARACTERS_QUERY } from "./graphql/queries/characters";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { getAccessToken } from '@auth0/nextjs-auth0/edge';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function SSRLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const apolloClient = initializeApollo({
    headers: {
      authorization: cookies().get("authToken")?.value ?? "",
    },
  });
  // Calling query here will cause the query to be executed on the server,
  // and persist into requestStorage.
  await apolloClient.query({ query: CHARACTERS_QUERY });

  return (
    <html lang="en">
      <ThemeRegistry>
        <UserProvider>
          <Apollo apolloState={JSON.stringify(getRequestStorage().apolloState ?? {})}>
            <body suppressHydrationWarning={true}>

              <ResponsiveAppBar />
              {children}

            </body>
          </Apollo>
        </UserProvider>
      </ThemeRegistry>
    </html>
  );
}

